create table if not exists public.news (
  id bigint generated by default as identity primary key,
  title text not null,
  link text not null,
  summary text,
  source text not null,
  created_at timestamptz not null default now()
);

create index if not exists news_created_at_idx on public.news (created_at desc);
create index if not exists news_link_idx on public.news (link);
