export const STORAGE_KEYS = {
  readMap: "news-hub.read-map",
  laterMap: "news-hub.later-map",
  notesMap: "news-hub.notes-map",
  sourcePrefs: "news-hub.source-prefs",
  savedViews: "news-hub.saved-views"
};

export const COPY = {
  title: "News Hub",
  subtitle:
    "少数の信頼ソースを毎日すばやく読むためのニュースワークスペースです。読む、残す、絞る、後で処理する、を1画面で回せるように再設計しています。",
  update: "最新を更新",
  updateLoading: "更新中...",
  syncSaved: "保存済みを同期",
  syncSavedLoading: "同期中...",
  searchTitle: "検索とビュー",
  searchHint:
    "最新フィード、保存済み、後で読む、未読を横断して検索できます。表示中のソース名やタイトルでそのまま絞り込めます。",
  searchPlaceholder: "タイトル・ソース・要約で検索",
  saveView: "ビュー保存",
  clear: "クリア",
  filtersTitle: "表示コントロール",
  filtersHint:
    "ノイズの少ない読み方に寄せるための設定です。Shorts非表示、未読優先、ソース単位の表示制御をまとめています。",
  hideShorts: "YouTube Shortsを隠す",
  unreadOnly: "未読だけ見る",
  hideMuted: "ミュートしたソースを隠す",
  groupTopics: "関連トピックをまとめる",
  sourceSettings: "ソース設定",
  captureTitle: "手動保存",
  captureHint:
    "URLとタイトルを直接入力して保存できます。保存先が未設定でも、まずは画面上で読む体験を優先しています。",
  feedTitle: "今日のフィード",
  feedHint: "いま読む記事を、横幅優先で見やすく表示",
  queueTitle: "後で読む",
  queueHint: "気になった記事を一時キューに退避",
  libraryTitle: "保存ライブラリ",
  libraryHint: "保存済み記事の保管庫",
  detailTitle: "記事ワークスペース",
  detailHint: "選択した記事のメモ、状態、関連情報を確認できます。",
  topicsTitle: "関連トピック",
  topicsHint: "似た見出しをまとめて一覧のノイズを減らします。",
  noTopics: "いまは似たトピックの束はありません。",
  emptyFeed: "ニュースを取得するとここに表示されます。",
  emptyQueue: "後で読む記事はまだありません。",
  emptyLibrary: "保存済みニュースはまだありません。",
  emptySearch: "一致する記事はありません。",
  idleSearch: "検索語を入力するか、保存したビューを選ぶとここに結果を表示します。",
  selectPrompt: "記事を1件選ぶと、メモと状態管理をここで続けられます。",
  savedUnavailable:
    "保存機能は現在利用できません。Supabase 環境変数が未設定のため、保存済み一覧と保存済み検索は動作しません。",
  notePlaceholder: "あとで見返すポイントや判断メモを書けます。",
  noSummary: "要約はまだありません。",
  unknownDate: "日時不明",
  sourceFallback: "その他",
  ready: "準備完了",
  busy: "更新中",
  savedReady: "保存機能は利用可能です。",
  savedMissing: "保存機能は未設定です。",
  open: "開く",
  detail: "詳細",
  summarize: "要約",
  summarizeLoading: "要約中...",
  save: "保存",
  saveLoading: "保存中...",
  markRead: "既読にする",
  markUnread: "未読に戻す",
  addLater: "後で読む",
  removeLater: "キュー解除",
  manualSave: "手動保存",
  manualSaving: "保存中..."
};
